name: Release Workflow

on:
  push:
    branches: ["master", "develop"]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set executable permissions
        run: |
          chmod +x ./ci/prepare.sh
          chmod +x ./ci/format_version.sh

      - name: Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          dotnet-version: 9

      - name: Add NuGet Source
        if: steps.semantic.outputs.new_release_published == 'true'
        run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Build
        if: steps.semantic.outputs.new_release_published == 'true'
        run: dotnet build -c Release

      - name: Pack NuGet Package
        if: steps.semantic.outputs.new_release_published == 'true'
        run: dotnet pack -c Release -o output

      - name: Publish to GitHub packages
        if: steps.semantic.outputs.new_release_published == 'true'
        run: dotnet nuget push output/*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      # - name: Publish to NuGet
      #   run: dotnet nuget push output/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
